import React from "react";

import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import { cookies } from "next/headers";

import { Toastify } from "@/components/Shared/Toast";
import { ITheme } from "@/hooks/useTheme";

import Providers from "./providers";

import "./globals.css";

const publicSans = Public_Sans({
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function getSystemTheme(): ITheme {
  if (typeof window !== "undefined" && window.matchMedia) {
    return window.matchMedia("(prefers-color-scheme: dark)").matches
      ? "dark"
      : "light";
  }
  return "light";
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const savedTheme = (await cookies()).get("color-theme");
  const getTheme = (savedTheme?.value as ITheme) || getSystemTheme();
  const theme = getTheme === "system" ? "dark" : getTheme;
  return (
    <html lang="en" className={theme} data-theme={theme}>
      <Providers initialTheme={getTheme}>
        <body className={`${publicSans.className}`}>
          {children} <Toastify />
        </body>
      </Providers>
    </html>
  );
}
